parameters:
#    projet_lol_search.example.class: Projet\LolSearchBundle\Example

services:
#    projet_lol_search.example:
#        class: %projet_lol_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
